---
aliveStatusCodes:
  - 200
files:
  - README.md
followRedirects: false
ignorePatterns:
  - pattern: "^https://cdn.rawgit.com"
  - pattern: "^https://codeberg.org"
  - pattern: "^https://git.sr.ht"
  - pattern: "^https://github.com/owner/repo"
  - pattern: "^https://gitlab.freedesktop.org"
