---
blank_issues_enabled: true
contact_links:
  - name: 💬 We are Wayland now!
    url: https://github.com/gianklug/wearewaylandnow
    about: Consider this instead if an application has *added* support for Wayland. 🤔
